### ISSUE TITLE
heartbeat < heartbeat_interval ?

### ISSUE THREAD

**Issue by pubnubcraig** [pubnub/angularjs-hubbub#3]
https://github.com/pubnub/angularjs-hubbub/blob/7d9268216a16ae31b83b2db38f82b4d530a61a93/client/app/app.config.js#L9

    heartbeat: 40,
    heartbeat_interval: 60

Should 40 be 240?

**Comment by supertinou** [comment]
Good call @pubnubcraig, thank you! this is fixed by https://github.com/pubnub/angularjs-hubbub/commit/f3a08a170a4835552581f56331975518ddd2d4c3
