### ISSUE TITLE
Follow the install instructions here and couldn't make it work

### ISSUE THREAD

**Issue by barak-haviv** [pubnub/angularjs-hubbub#6]
If I use the install instruction as it is ( I check myself several times )
I get 

> redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application

from github
if I change the github url to http://localhost:9000/ 
I get github auth page in new window and I can authorized it 
I can see in my github account that it works
But in the the app
I get authentication failed.

**Comment by supertinou** [comment]
Hi @barak-haviv, 

Which value is set for the **GITHUB_ACCESS_TOKEN_REQUEST_URL** key in the **client/sample.config.json** ? 
It should be the address of the NodeJS server (Usually http://localhost:9000/). 

Once you are successfully authenticated to Github, Github OAuth is pass an authorization code to the AngularJS app and the AngularJS app reach the NodeJS server and pass this authorization token in order to authenticate the user.
![Flow](https://www.pubnub.com/wp-content/uploads/2016/04/github-oauth2-server-flow.png)

**Comment by niroshannrsh** [comment]
i also face same problem .How  to solve it ? plz update guideline?

**Comment by karelbecerra** [comment]
Almost same issue. I changed a few things:

Gitup:
 home url = http://localhost:9000
 call back url = http://localhost:9000

config.json
	"GITHUB_REDIRECT_URI": "http://localhost:9000",
	"GITHUB_ACCESS_TOKEN_REQUEST_URL": "http://localhost:3000/auth/github",
	"SERVER_URL": "http://localhost:3000/"

.env
GITHUB_REDIRECT_URI=http://localhost:9000
GITHUB_ACCESS_TOKEN_REQUEST_URL=http://localhost:3000/auth/github

Steps:
1- ok
2- ok
3- ok
4- ok
5- ok
?? Auth fails however I'm able to see the user row in users.db

**Comment by aguirre1017** [comment]
Same issue here. I was able to successfully login on the app but somehow the app is kicking me away going back to login again. I am able to see logs at users.db file. What seems to be the issue here?

**Comment by supertinou** [comment]
@barak-haviv, @niroshannrsh, @karelbecerra, @aguirre1017 
Please ensure that :
- You have created your own PubNub application and are using your own credentials (publish key, subscribe_key, secret key)
- The following add-ons are enabled for your PubNub application : 
PRESENCE, ACCESS MANAGER, STORAGE & PLAYBACK and STREAM CONTROLLER.
- You have created you own Github OAuth2 app here : https://github.com/settings/developers
- The **Authorization callback URL**  
![screen shot 2016-11-14 at 12 02 13 am](https://cloud.githubusercontent.com/assets/1976010/20257382/13e64dd2-a9fe-11e6-97ff-8156f8c700e1.png)

matches exactly the value of the **GITHUB_ACCESS_TOKEN_REQUEST_URL** field specified in **client/config.json** and **server/.env**

Please let me know if it helped or if you are still facing the issue.
