### ISSUE TITLE
Api get conversation and friends error 500

### ISSUE THREAD

**Issue by Naqued** [pubnub/angularjs-hubbub#7]
Hello,
i have follow all the instruction but i'm blocking on something.
Everything is going well till the server do a "Get /api/conversation and /api/friend" where i get an Error code 500

OPTIONS /api/friends/ 204 0.468 ms - -
OPTIONS /api/conversations/ 204 0.216 ms - -
GET /api/conversations/ 500 167.604 ms - -
GET /api/friends/ 500 1408.185 ms 

in the instruction i just change one thing : the url callback on my Github profile to http://localhost:9000.
Otherwise i get an error like the callback and the uri_redirect must be the same

Can you help me ?

Thanks

**Comment by supertinou** [comment]
Hi @Naqued,
Can you send an email to support@pubnub.com ?

**Comment by Naqued** [comment]
Hi @supertinou, yes i have send an email. I'm waiting the answer

**Comment by DPoSign** [comment]
Hello I just got the same error

OPTIONS /api/friends/ 204 0.942 ms - -
OPTIONS /api/conversations/ 204 0.385 ms - -
GET /api/conversations/ 500 170.943 ms - -
GET /api/friends/ 500 999.617 ms - -

Anyone have a solution ?

**Comment by Naqued** [comment]
I have wrote to the support, @supertinou is looking on it

**Comment by DPoSign** [comment]
They answered your ticket ? Great then ! I really enjoyed this tutorial but it's frustrating to be blocked just before the end

**Comment by Naqued** [comment]
He answered first yea, i'm waiting another respons because he needed more details.
If i get any solution, i'll wrote it

**Comment by DPoSign** [comment]
Thank you ! 😄

**Comment by supertinou** [comment]
@Naqued, @DPoSign ,
Please check that the following Add-ons are enabled for your PubNub application : 
PRESENCE, ACCESS MANAGER, STORAGE & PLAYBACK and STREAM CONTROLLER.

Please let me know if it solved your issue. 
I will add a note to remind to enable the Add-ons.

**Comment by DPoSign** [comment]
I just solved the problem easily, thank you very much!

Merci pour votre tutoriel, il est génial ;)

**Comment by supertinou** [comment]
@DPoSign, awesome, merci :)

**Comment by Naqued** [comment]
that solve the problem for me too !!
Thanks :)

**Comment by supertinou** [comment]
@Naqued, good news!
